################################
#   GENERIC SERVER PROPERTIES  #
################################

server.port=7338

app.name=GraphQL Connector
app.description=${app.name} is a Composer EDC connector for GraphQL APIs

spring.main.banner_mode=console
banner.charset=UTF-8
banner.location=classpath:banner.txt

######################
#  SYSLOG PROPERTIES #
######################

syslog.host=localhost
syslog.port=514
syslog.log.level=OFF
syslog.suffix=GQL

#########################
#  GRAPHQL PROPERTIES   #
#########################

graphql.connection.timeout.sec=30
graphql.read.timeout.sec=60

#########################
#  ACTUATOR PROPERTIES  #
#########################

management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoints.web.exposure.include=health

####################################
# DATA SOURCE POOL PROPERTIES      #
####################################

datasource.min.idle=0
datasource.max.idle=5
datasource.max.active=100
datasource.max.idle.time.sec=5
datasource.max.wait.time.sec=20
datasource.eviction.time.between.sec=1
